description: Take a second snapshot and finalize the comparison tests.
id: PAN-OS Network Operations - Upgrade Assurance - Assurance Test
inputs:
- description: ""
  key: target
  playbookInputQuery:
  required: false
  value:
    simple: ${incident.panosnetworkoperationstarget}
name: PAN-OS Network Operations - Upgrade Assurance - Assurance Test
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d8d4736a-b230-405e-8f1f-aec707cd0cc1
      iscommand: false
      name: ""
      version: -1
    taskid: d8d4736a-b230-405e-8f1f-aec707cd0cc1
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    fieldMapping:
    - incidentfield: Second Snapshot ID
      output:
        complex:
          accessor: EntryID
          root: File
          transformers:
          - operator: LastArrayElement
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      check_list:
        simple: ${incident.snapshotchecklist}
      firewall_serial:
        simple: ${inputs.target}
      snapshot_name:
        simple: second_snapshot
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Takes a snapshot of the operational state of the system.
      id: 7da774dc-6b8b-452c-8c5d-06d2555f44be
      iscommand: true
      name: Take the Second snapshot
      script: "|||pan-os-assurance-run-snapshot"
      type: regular
      version: -1
    taskid: 7da774dc-6b8b-452c-8c5d-06d2555f44be
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    fieldMapping:
    - incidentfield: Snapshot Comparison Result
      output:
        simple: ${FirewallAssurance.SnapshotComparisonResult}
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      check_list:
        simple: ${incident.snapshotchecklist}
      left_snapshot_id:
        simple: ${incident.firstsnapshotid}
      right_snapshot_id:
        simple: ${incident.secondsnapshotid}
      session_stats_threshold:
        simple: ${incident.sessionstatschangethreshold}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Takes a snapshot of the operational state of the system.
      id: 79a534d6-b247-4c52-8a6d-a81acd274e0d
      iscommand: true
      name: Run Comparsion
      script: "|||pan-os-assurance-compare-snapshots"
      type: regular
      version: -1
    taskid: 79a534d6-b247-4c52-8a6d-a81acd274e0d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 550
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      body:
        simple: '{"field": "secondsnapshot"}'
      entryID:
        complex:
          accessor: secondsnapshotid
          root: incident
      incID:
        simple: ${incident.id}
      target:
        simple: incident attachment
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Copies a file from this incident to the specified incident. The
        file is recorded as an entry in the specified incident’s War Room.
      id: 69b270a2-c433-421c-8e8d-b715d54fe1c4
      iscommand: false
      name: Save Second Snapshot
      script: UploadFile
      type: regular
      version: -1
    taskid: 69b270a2-c433-421c-8e8d-b715d54fe1c4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 380
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      comparisontestraw:
        simple: |-
          # Raw Comparison test result (JSON)

          ```json
          ${FirewallAssurance.SnapshotComparisonRawResult}
          ```
      upgradeassurancereport:
        simple: |
          ${incident.upgradeassurancereport}
          ## Comparison checks FAILED

          ${incident.snapshotcomparisonresult(val.passed=='false')=>x(val);
              function x(v) {
                  s = ""
                  if (v.length == 0) {
                      return "✅ All Tests Passing! ✅";
                  }
                  v.forEach(function(item){
                      s = s + " *  ❌ " + item.test + "\n";
                  })
                  return s;
              };
          }

          ## Comparison checks PASSED

          ${incident.snapshotcomparisonresult(val.passed=='true')=>x(val);
              function x(v) {
                  s = ""
                  if (v.length == 0) {
                      return "❌ All tests failing! ❌";
                  }
                  v.forEach(function(item){
                      s = s + " * " + item.test + "\n";
                  })
                  return s;
              };
          }
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 073bf225-8e62-400c-8ab4-b9514dbe6d12
      iscommand: true
      name: Update Incident
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 073bf225-8e62-400c-8ab4-b9514dbe6d12
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 720
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: FirewallAssurance.SnapshotComparisonResult.passed
                    operator: isEqualString
                    right:
                      value:
                        simple: "false"
                root: FirewallAssurance.SnapshotComparisonResult
          operator: isExists
          right:
            value: {}
        - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: incident.readinesscheckresult.state
                    operator: isEqualString
                    right:
                      value:
                        simple: "false"
                root: incident.readinesscheckresult
          operator: isExists
      label: FAILED
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      FAILED:
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 44664e04-a007-483c-8dc9-381f0eb33e42
      iscommand: false
      name: Overall Result
      type: condition
      version: -1
    taskid: 44664e04-a007-483c-8dc9-381f0eb33e42
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 900
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      assurancetestresult:
        simple: Failed ❌
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 0937285e-735f-40d3-8d87-7a48f4612729
      iscommand: true
      name: Tests Failed
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 0937285e-735f-40d3-8d87-7a48f4612729
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1090
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      assurancetestresult:
        simple: Passed ✅
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 85f128a9-62ed-4984-8777-2f9aea615d4e
      iscommand: true
      name: Tests Passed
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 85f128a9-62ed-4984-8777-2f9aea615d4e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 840,
          "y": 1090
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: FirewallAssurance.SnapshotComparisonResult.passed
                    operator: isEqualString
                    right:
                      value:
                        simple: "false"
                root: FirewallAssurance.SnapshotComparisonResult
          operator: isExists
          right:
            value: {}
      label: FAILED
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "10"
      FAILED:
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: badf997a-d2cf-40f6-8d23-3b307f75c647
      iscommand: false
      name: Comparison result
      type: condition
      version: -1
    taskid: badf997a-d2cf-40f6-8d23-3b307f75c647
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -20,
          "y": 900
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      assurancetestresult:
        simple: Failed ❌
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: d13f375e-8a33-4330-884e-55c279fcc239
      iscommand: true
      name: Comparison Tests Failed
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: d13f375e-8a33-4330-884e-55c279fcc239
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -20,
          "y": 1090
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      assurancetestresult:
        simple: Passed ✅
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: cf591376-d930-4170-804e-92a4dde36445
      iscommand: true
      name: Comparison Tests  Passed
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: cf591376-d930-4170-804e-92a4dde36445
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -430,
          "y": 1090
        }
      }
version: 22
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1135,
        "width": 1650,
        "x": -430,
        "y": 50
      }
    }
  }
