description: Runs a complete upgrade process for a single device
id: PAN-OS Network Operations - Single Device Upgrade
inputs:
- description: Target firewall to upgrade
  key: target
  playbookInputQuery: null
  required: true
  value: {}
- description: Target version to upgrade to.
  key: target_version
  playbookInputQuery: null
  required: true
  value: {}
name: PAN-OS Network Operations - Single Device Upgrade
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "25"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 91eefe42-28fe-4378-802a-e23dba37b3e1
      iscommand: false
      name: ""
      version: -1
    taskid: 91eefe42-28fe-4378-802a-e23dba37b3e1
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -2110
        }
      }
  "14":
    continueonerror: true
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    scriptarguments:
      hostid:
        simple: ${inputs.target}
      target:
        simple: ${inputs.target}
      using:
        simple: ${incident.panosnetworkoperationspanoramainstance}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Reboots the given device by host ID. Warning: This command has no confirmation and the device will immediately reboot. This command can be disruptive.
      id: 0db2708f-681f-4316-89be-ac62538313e5
      iscommand: true
      name: Reboot the system
      script: '|||pan-os-platform-reboot'
      type: regular
      version: -1
    taskid: 0db2708f-681f-4316-89be-ac62538313e5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": -65
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: using
      AdditionalPollingCommandArgValues:
        simple: ${incident.panosnetworkoperationspanoramainstance}
      Ids:
        simple: ${inputs.target}
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: target
      PollingCommandName:
        simple: pan-os-platform-get-system-status
      Timeout:
        simple: "60"
      dt:
        simple: PANOS.SystemStatus(!val.up).hostid
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 2c3f9056-3964-47f0-84dd-868f12e294d9
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 2c3f9056-3964-47f0-84dd-868f12e294d9
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 300
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Finish
      id: 14a0d3de-2b94-41c9-8150-04caf462b276
      iscommand: false
      name: Finish
      type: title
      version: -1
    taskid: 14a0d3de-2b94-41c9-8150-04caf462b276
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 825
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      using:
        simple: ${incident.panosnetworkoperationspanoramainstance}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets information from all PAN-OS systems in the topology.
      id: daa9f32d-51c5-4a8b-866b-df82731115f5
      iscommand: true
      name: Get System Info
      script: '|||pan-os-platform-get-system-info'
      type: regular
      version: -1
    taskid: daa9f32d-51c5-4a8b-866b-df82731115f5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 450
        }
      }
  "19":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PANOS.ShowSystemInfo.Result.sw_version
          operator: isEqualString
          right:
            iscontext: true
            value:
              simple: inputs.target_version
      label: "yes"
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "20"
      "yes":
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether the post-upgrade software version is correct.
      id: 8df2b9df-d39a-46be-85a8-d74d1a186222
      iscommand: false
      name: Check System running new version
      type: condition
      version: -1
    taskid: 8df2b9df-d39a-46be-85a8-d74d1a186222
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 630
        }
      }
  "20":
    continueonerrortype: ""
    id: "20"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      message:
        simple: Installation completed, reboot completed, but device still on old
          software version.
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints an error entry with a given message
      id: 9f37d112-b591-49a6-896c-6eebd982c6b2
      iscommand: false
      name: Fail message
      script: PrintErrorEntry
      type: regular
      version: -1
    taskid: 9f37d112-b591-49a6-896c-6eebd982c6b2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 810
        }
      }
  "21":
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "25"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: 4fae2bf8-e8cf-4074-81c0-83ce539865fd
      iscommand: false
      name: Sleep to let device shutdown gracefully
      script: Sleep
      type: regular
      version: -1
    taskid: 4fae2bf8-e8cf-4074-81c0-83ce539865fd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 110
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "35"
    note: false
    quietmode: 0
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      using:
        simple: ${incident.panosnetworkoperationspanoramainstance}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks the devices for software that is available to be installed.
      id: b7231fc3-6762-422e-8af1-676bfae38c06
      iscommand: true
      name: Get Available Software
      script: '|||pan-os-platform-get-available-software'
      type: regular
      version: -1
    taskid: b7231fc3-6762-422e-8af1-676bfae38c06
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": -1460
        }
      }
  "23":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: version
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: PANOS.SoftwareVersions.Summary.downloaded
                    operator: isTrue
                root: PANOS.SoftwareVersions.Summary
          operator: containsGeneral
          right:
            iscontext: true
            value:
              simple: inputs.target_version
      label: "yes"
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "38"
      "yes":
      - "39"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the upgrade software version is already downloaded onto
        the PAN-OS system.
      id: a846ea9d-4cd6-40f1-8b8f-fb2b663ae69a
      iscommand: false
      name: Has the software already been downloaded?
      type: condition
      version: -1
    taskid: a846ea9d-4cd6-40f1-8b8f-fb2b663ae69a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": -760
        }
      }
  "24":
    continueonerror: true
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    scriptarguments:
      using:
        simple: ${incident.panosnetworkoperationspanoramainstance}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Get the device state from the provided device. Note; This will
        attempt to connect directly to the provided target to get the device state.
        If the IP address as reported in "show system info" is unreachable, this command
        will fail.
      id: c8659392-64c4-496e-8d32-684166f7137d
      iscommand: true
      name: Save Device State
      script: '|||pan-os-platform-get-device-state'
      type: regular
      version: -1
    taskid: c8659392-64c4-496e-8d32-684166f7137d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": -1640
        }
      }
  "25":
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    scriptarguments:
      device_filter_string:
        simple: ${inputs.target}
      using:
        simple: ${incident.panosnetworkoperationspanoramainstance}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Gets information from all PAN-OS systems in the topology.
      id: c1a50873-1b07-486b-8a23-b0bf9dad9515
      iscommand: true
      name: Get System Info
      script: '|||pan-os-platform-get-system-info'
      type: regular
      version: -1
    taskid: c1a50873-1b07-486b-8a23-b0bf9dad9515
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": -1980
        }
      }
  "26":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: PANOS.ShowSystemInfo.Summary.family
          operator: isEqualString
          right:
            value:
              simple: pc
      label: Panorama
    continueonerrortype: ""
    id: "26"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "24"
      Panorama:
      - "22"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks the system type.
      id: 231634fd-c635-4eb7-8376-b4e52c37a671
      iscommand: false
      name: System Type
      type: condition
      version: -1
    taskid: 231634fd-c635-4eb7-8376-b4e52c37a671
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": -1830
        }
      }
  "27":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: BaseImage
          operator: in
          right:
            iscontext: true
            value:
              complex:
                accessor: version
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: PANOS.SoftwareVersions.Summary.downloaded
                    operator: isTrue
                root: PANOS.SoftwareVersions.Summary
      label: "yes"
    continueonerrortype: ""
    id: "27"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "37"
      "yes":
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: True if the base version of the upgrade image is downloaded.
      id: 90712f87-915f-4399-8a0d-d1735010e9a2
      iscommand: false
      name: Is the base version of this image downloaded?
      type: condition
      version: -1
    taskid: 90712f87-915f-4399-8a0d-d1735010e9a2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": -1110
        }
      }
  "35":
    continueonerrortype: ""
    id: "35"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "27"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: BaseImage
      value:
        complex:
          root: inputs.target_version
          transformers:
          - args:
              delimiter:
                value:
                  simple: .
            operator: split
          - args:
              from:
                value:
                  simple: "0"
              to:
                value:
                  simple: "2"
            operator: slice
          - args:
              separator:
                value:
                  simple: .
            operator: join
          - args:
              prefix: {}
              suffix:
                value:
                  simple: ".0"
            operator: concat
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: aadc01bb-b203-45a6-86e0-dd226ffdfdf6
      iscommand: false
      name: Set BASE Software Version
      script: Set
      type: regular
      version: -1
    taskid: aadc01bb-b203-45a6-86e0-dd226ffdfdf6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": -1300
        }
      }
  "37":
    continueonerrortype: ""
    id: "37"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      target:
        simple: ${inputs.target}
      target_version:
        simple: ${BaseImage}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: Downloads the PAN-OS Software.
      id: b63a7458-78a2-4c99-8290-542f5a55a065
      iscommand: false
      name: PAN-OS Network Operations - Download Software
      playbookId: PAN-OS Network Operations - Download Software
      type: playbook
      version: -1
    taskid: b63a7458-78a2-4c99-8290-542f5a55a065
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 690,
          "y": -930
        }
      }
  "38":
    continueonerrortype: ""
    id: "38"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "39"
    note: false
    quietmode: 0
    scriptarguments:
      target:
        simple: ${inputs.target}
      target_version:
        simple: ${inputs.target_version}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: Downloads the given software image.
      id: 671fdb2c-f704-4105-814a-81fb59c07de1
      iscommand: false
      name: PAN-OS Network Operations - Download Software
      playbookId: PAN-OS Network Operations - Download Software
      type: playbook
      version: -1
    taskid: 671fdb2c-f704-4105-814a-81fb59c07de1
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 690,
          "y": -565
        }
      }
  "39":
    continueonerrortype: ""
    id: "39"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "40"
    note: false
    quietmode: 0
    scriptarguments:
      target:
        simple: ${inputs.target}
      target_version:
        simple: ${inputs.target_version}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: Run the installation subplaybook.
      id: cb311a34-a34b-4623-870e-fb78275320f8
      iscommand: false
      name: PAN-OS Network Operations - Install Software
      playbookId: PAN-OS Network Operations - Install Software
      type: playbook
      version: -1
    taskid: cb311a34-a34b-4623-870e-fb78275320f8
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": -375
        }
      }
  "40":
    continueonerrortype: ""
    id: "40"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    scriptarguments:
      description:
        simple: Rebooting System
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: bc674cab-fb7f-44c0-8a1d-9b864f3f64c0
      iscommand: true
      name: Set Status
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: bc674cab-fb7f-44c0-8a1d-9b864f3f64c0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": -220
        }
      }
version: 7
view: |-
  {
    "linkLabelsPosition": {
      "23_38_#default#": 0.64
    },
    "paper": {
      "dimensions": {
        "height": 3015,
        "width": 840,
        "x": 450,
        "y": -2110
      }
    }
  }
