description: Checks to see if this incident has a parent incident and if so, links
  the two incidents.
id: PAN-OS Network Operations - Incident Callback
inputs: []
name: PAN-OS Network Operations - Incident Callback
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: de5eacbb-9481-4507-8258-3acff97cabe5
      iscommand: false
      name: ""
      version: -1
    taskid: de5eacbb-9481-4507-8258-3acff97cabe5
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 20
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      id:
        simple: ${incident.panosnetworkoperationsclosetaskid}
      incidentId:
        simple: ${incident.panosnetworkoperationsparentincidentid}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.task.complete
      id: 230cc56a-1b12-4dcc-8373-b21b3a02cf56
      iscommand: true
      name: Mark Complete
      script: Builtin|||taskComplete
      type: regular
      version: -1
    taskid: 230cc56a-1b12-4dcc-8373-b21b3a02cf56
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 330
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: dc183a2b-a042-4d8b-8064-c20b35293609
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: dc183a2b-a042-4d8b-8064-c20b35293609
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 490
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident.panosnetworkoperationsclosetaskid
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Chefcks if the incident callback needs to run.
      id: 19f083a6-1a32-4f23-8efc-ad4989cbcb9f
      iscommand: false
      name: Do we have a parent task to mark complete?
      type: condition
      version: -1
    taskid: 19f083a6-1a32-4f23-8efc-ad4989cbcb9f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 150
        }
      }
version: 7
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 535,
        "width": 380,
        "x": 450,
        "y": 20
      }
    }
  }
