description: Runs a series of tests based on the upgrade assurance commands and prompts
  if any fail - also generates reports and other information that is useful in the
  assurance process.
id: PAN-OS Network Operations - Upgrade Assurance
inputs:
- description: Target firewall - helpful if running this playbook in a loop.
  key: target
  playbookInputQuery: null
  required: true
  value:
    simple: ${incident.panosnetworkoperationstarget}
name: PAN-OS Network Operations - Upgrade Assurance
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b8463b92-38b1-46ae-821e-e6c895b59a1b
      iscommand: false
      name: ""
      version: -1
    taskid: b8463b92-38b1-46ae-821e-e6c895b59a1b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      description:
        simple: Assurance testing aborted.
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 3789ab9c-f5d1-49e3-884f-a1a67a495cc2
      iscommand: true
      name: Aborted process.
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 3789ab9c-f5d1-49e3-884f-a1a67a495cc2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 860,
          "y": 880
        }
      }
  "7":
    continueonerrortype: ""
    form:
      description: Mark complete when you're ready to take the second snapshot and
        run the comparsion between the two.
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: |-
            ### Do you want to continue?
            *Choosing Yes will run the second snapshot, and proceed with the comparsion*
        options: []
        optionsarg:
        - simple: "Yes"
        - simple: "No"
        placeholder: ""
        readonly: false
        required: true
        tooltip: ""
        type: singleSelect
      sender: Your SOC team
      title: Second Snapshot Confirmation
      totalanswers: 0
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body:
        simple: 'The assurance process is paused, waiting for manual confirmation
          to take the second snapshot and run the comparsion on firewall ${incident.panosnetworkoperationsupgradetargetfirewall}. '
      cc: null
      format: ""
      methods:
      - email
      subject:
        simple: Waiting for trigger for Snapshot on ${incident.panosnetworkoperationsupgradetargetfirewall}
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
        simple: ${incident.owner}
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b862ab81-e717-466d-8d23-033ca4ad32c7
      iscommand: false
      name: Second Snapshot Trigger
      type: collection
      version: -1
    taskid: b862ab81-e717-466d-8d23-033ca4ad32c7
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 450,
          "y": 350
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Second Snapshot Confirmation.Answers.0
          operator: isEqualString
          right:
            value:
              simple: "Yes"
      label: "yes"
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e34dd71d-28ff-4067-89a0-dbef5dbad4bf
      iscommand: false
      name: Continue?
      type: condition
      version: -1
    taskid: e34dd71d-28ff-4067-89a0-dbef5dbad4bf
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 520
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 280cd7cd-a56d-424f-8aad-dbf2b88c7476
      iscommand: false
      name: PAN-OS Network Operations - Upgrade Assurance - First Snapshot
      playbookId: PAN-OS Network Operations - Upgrade Assurance - First Snapshot
      type: playbook
      version: -1
    taskid: 280cd7cd-a56d-424f-8aad-dbf2b88c7476
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 5bd44314-3cc0-4a9c-8da5-a237fde0d080
      iscommand: false
      name: PAN-OS Network Operations - Upgrade Assurance - Assurance Test
      playbookId: PAN-OS Network Operations - Upgrade Assurance - Assurance Test
      type: playbook
      version: -1
    taskid: 5bd44314-3cc0-4a9c-8da5-a237fde0d080
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 880
        }
      }
version: 29
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 925,
        "width": 790,
        "x": 450,
        "y": 50
      }
    }
  }
