name: Releases

on:
  push:
    tags:
      - '*'

jobs:

  zip_and_release:
    name: "Package ZIP And upload as release."
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: "Set up Python 3.10"
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest demisto-sdk
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Create content zip
        run: |
          demisto-sdk zip-packs -i Packs/PAN_OS_Upgrade_Services/ -o /tmp
      - uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1
        with:
          artifacts: "/tmp/uploadable_packs/PAN_OS_Upgrade_Services.zip"
          bodyFile: "release.md"