name: Python package

on: [push]

jobs:
  build_and_test:
    name: "Build, test, and check for secrets."
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest demisto-sdk
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Runn all tests with Pytest
        run: |
          pytest
      - name: Check for Secrets
        run: |
          demisto-sdk secrets -wl secrets_ignore_whitelist.json